version: "2"
services:
  orderServer:
    image: teezily/ftpd
    environment:
      - FTP_USER=admin
      - FTP_PASSWORD=admin
      - HOST=localhost
      - PASV_MIN_PORT=65000
      - PASV_MAX_PORT=65004
    ports:
      - "11021:21"
      - "65000-65004:65000-65004"
